# Generated by Django 5.2.5 on 2025-09-04 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='工序名称')),
                ('description', models.TextField(blank=True, verbose_name='工序描述')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='工艺路线名称')),
            ],
        ),
        migrations.CreateModel(
            name='RouteProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='工序顺序')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.process', verbose_name='工序')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.route', verbose_name='工艺路线')),
            ],
            options={
                'verbose_name': '工艺路线工序关系',
                'verbose_name_plural': '工艺路线工序关系',
                'ordering': ['order'],
                'unique_together': {('route', 'process')},
            },
        ),
        migrations.AddField(
            model_name='route',
            name='processes',
            field=models.ManyToManyField(related_name='routes', through='app.RouteProcess', through_fields=('route', 'process'), to='app.process', verbose_name='关联工序'),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='工单名称')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已审核'), ('scheduled', '已排产')], default='draft', max_length=20, verbose_name='状态')),
                ('route', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.route', verbose_name='工艺路线')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '未生产'), ('unreported', '未报工'), ('in_progress', '进行中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='任务状态')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.process', verbose_name='关联工序')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.workorder', verbose_name='关联工单')),
            ],
        ),
    ]
