# Generated by Django 5.2.5 on 2025-09-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('unreported', '未报工'), ('in_progress', '进行中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='任务状态'),
        ),
    ]
