# Generated by Django 5.2.5 on 2025-09-04 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routeprocess',
            unique_together={('route', 'order')},
        ),
        migrations.AddField(
            model_name='task',
            name='route_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.routeprocess', verbose_name='关联工艺路线工序关系'),
        ),
    ]
