# Generated by Django 5.2.5 on 2025-09-03 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.route', verbose_name='工艺路线'),
        ),
    ]
