# Generated by Django 5.2.5 on 2025-09-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_workorder_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='route',
        ),
        migrations.AddField(
            model_name='workorder',
            name='processes',
            field=models.ManyToManyField(related_name='work_orders', to='app.process', verbose_name='关联工序'),
        ),
    ]
